version: 2.1
jobs:
  run-build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - node/install-packages
      - run: npm build
  run-test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - node/install-packages
      - run: npm test
  run-analysis:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - node/install-packages
      - run: npm run analyze-bundle
workflows:
  deployment:
    - run-build
    - run-test:
        requires:
          - run-build
    - run-analysis:
        requires:
          - run-test
    